env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - "amd64"

archives:
  -
    format_overrides:
      - goos: windows
        format: zip
    files:
      - scripts/*
      - README.md
      - CHANGELOG.md
      - Makefile
